[package]
name = "time-report"
version = "1.3.0"
edition = "2024"

[dependencies]
regex = "1"
im = "15.1.0"
lazy_static = "1"
derive-getters = "0.5.0"
chrono = "0.4"
rand = "0.9.1"
scopeguard = "1.2.0"
crossterm = "0"
itertools = "0"
